[package]
name = "d01-serde-and-serde-json"
version = "0.1.0"
edition = "2024"

#______________________________________________________________________________

[dependencies]
#______________________________________________________________________________

serde = { 
    version = "1.0.229", 
    features = ["derive"] 
}

# This was added using:
# cargo add serde --features derive

#______________________________________________________________________________

serde_json = "1.0.151"

# This was added using:
# cargo add serde_json

#______________________________________________________________________________
